# Generated by Django 3.2.5 on 2022-12-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221124_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[
                 ('register', '邮箱注册'), ('forget', '忘记密码')], max_length=10, verbose_name='发送类型')),
                ('send_time', models.DateTimeField(
                    auto_now_add=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'db_table': 'emailpro',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='激活'),
        ),
    ]
