# Generated by Django 3.2.5 on 2022-12-11 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221211_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='userinfo',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='user.userinfo'),
        ),
    ]
