# Generated by Django 3.2.5 on 2022-12-19 10:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_sports_record_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 18, 57, 6, 75446), verbose_name='日期时间'),
        ),
        migrations.CreateModel(
            name='Medicine_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('medicine_type', models.CharField(max_length=64, null=True, verbose_name='用药种类')),
                ('notes', models.CharField(max_length=64, null=True, verbose_name='备注')),
                ('quantity', models.FloatField(null=True, verbose_name='数量')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 12, 19, 18, 57, 6, 75613), verbose_name='日期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medicine_record', to='user.userinfo')),
            ],
        ),
    ]
