# Generated by Django 3.2.5 on 2022-12-20 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221219_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 9, 27, 36, 333810), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 9, 27, 36, 333810), verbose_name='日期时间'),
        ),
    ]
