# Generated by Django 3.2.5 on 2022-12-21 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 17, 1, 55, 975719), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 17, 1, 55, 975541), verbose_name='日期时间'),
        ),
    ]
