# Generated by Django 4.0.4 on 2023-01-07 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20221221_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 22, 24, 34, 934088), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='userinfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 22, 24, 34, 933700), verbose_name='日期时间'),
        ),
    ]
