# Generated by Django 4.0.4 on 2023-01-07 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='Alice', max_length=64, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 33, 42, 418244), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 33, 42, 417863), verbose_name='日期时间'),
        ),
    ]
