# Generated by Django 4.0.4 on 2023-01-07 17:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userinfo_nickname_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='出生日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 42, 34, 980021), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 42, 34, 979654), verbose_name='日期时间'),
        ),
    ]
