# Generated by Django 4.0.4 on 2023-01-07 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_patientinfo_birthday_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 45, 16, 392419), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 45, 16, 391209), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 1, 45, 16, 392056), verbose_name='日期时间'),
        ),
    ]
