# Generated by Django 4.0.4 on 2023-01-07 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='nickname',
            field=models.CharField(default='Alice', max_length=64, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 2, 21, 22, 62301), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 2, 21, 22, 61056), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 2, 21, 22, 61925), verbose_name='日期时间'),
        ),
    ]
