# Generated by Django 4.0.4 on 2023-01-08 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_userinfo_nickname_patientinfo_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 10, 57, 3, 416101), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 10, 57, 3, 414646), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 10, 57, 3, 415682), verbose_name='日期时间'),
        ),
    ]
