# Generated by Django 4.0.4 on 2023-01-08 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 26, 35, 828606), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 26, 35, 826788), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 26, 35, 828107), verbose_name='日期时间'),
        ),
        migrations.CreateModel(
            name='MedicineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medicinetime', to='user.userinfo')),
            ],
        ),
    ]
