# Generated by Django 4.0.4 on 2023-01-08 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_medicine_record_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 28, 20, 611403), verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 28, 20, 609670), verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='sports_record',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 8, 19, 28, 20, 611012), verbose_name='日期时间'),
        ),
    ]
